CONTRIBUTING.md

The link to the recipe repository did not work, so I changed the url.

fixed broken link to recipe repository

---

README.md

List package dependencies, node module compilation fixes
This helps #3 
I'm using Linux Mint 18.2.
This should will work on all distributions based on Ubuntu 16.04 or superior.

Add Linux (Debian/Ubuntu) build instructions

---

src/components/services/content/ServiceWebview.js
src/components/ui/StatusBarTargetUrl.js
src/styles/main.scss
src/styles/status-bar-target-url.scss

This resolves #47
PS.: Last PR was buggy and broke some previous commits. Sorry about that :(
This helps to avoid link scams
OS: Linux Mint 18.1 (Ubuntu 16.04)
Can you guys help to test in other platforms?

Show url when mouse enters a link

---

src/index.js

Fixes #29
Added `app.makeSingleInstance` to index.js

fix(App): Force Franz to use single window

---

src/lib/Menu.js

fix(Shortcut): Add ctrl+= alias for zoom in

---

src/stores/ServicesStore.js

This PR solves an issue with the app freezing after importing services.

fix(Service Import): Fix issue with import of on-premise services

---

src/webview/notifications.js

Recipe Notification API refactor

---

package.json
src/index.js

Open Window when app is pinned to taskbar and minimized to system tray

---

package.json
src/stores/AppStore.js
yarn.lock

fix(macOS): Fix launch Franz on start override

---

CHANGELOG.md
package.json
src/index.js

* **Windows:** Fix issue with multiple close handlers that prevent the app from quitting  ([eea593e](https://github.com/meetfranz/franz/commit/eea593e))

Beta 13 hotfix

---

src/components/services/content/ServiceDisabled.js
src/components/services/content/ServiceWebview.js
src/components/services/content/Services.js
src/components/services/content/WebviewCrashHandler.js
src/components/services/tabs/TabBarSortableList.js
src/components/services/tabs/TabItem.js
src/components/services/tabs/Tabbar.js
src/components/settings/settings/EditSettingsForm.js
src/config.js
src/containers/layout/AppLayoutContainer.js
src/containers/settings/EditSettingsScreen.js
src/i18n/locales/en-US.json
src/stores/AppStore.js
src/stores/ServicesStore.js
src/stores/SettingsStore.js
src/styles/services.scss
src/styles/tabs.scss

This PR adds a new option to display disabled service tabs (`default: true`)
Closes #192

Add option to show disabled services in tab bar

---

src/index.js

fix(macOS): Fix the need for the High Pref GPU

---

src/components/ui/AppLoader.js
src/components/ui/Loader.js

The spinner when loading the app is finally consistent with the overall design

Fix app loader spinner color

---

src/components/ui/Subscription.js
src/i18n/locales/en-US.json
src/lib/Miner.js
src/stores/UserStore.js
src/styles/settings.scss
src/styles/subscription.scss

- Add EU sales tax info
- Disable miner on windows (test)
- Replace miner with non-flagged version

Pricing Info

---

appveyor.yml
electron-builder.yml

fix(Windows): Fix notifications on Windows 10

---

src/lib/Miner.js

fix(Support with CPU): Reduce maximum CPU usage

---

.travis.yml
README.md
appveyor.yml
electron-builder.yml
package.json
yarn.lock

- Add tar.gz as a linux build target
- Use node 8 on travis
- Add gulp as a local dependency
- Remove gulp as a global dependency

[PR] build setup

---

gulpfile.babel.js
src/api/server/LocalApi.js
src/components/settings/settings/EditSettingsForm.js
src/models/Settings.js
src/stores/SettingsStore.js
src/webview/plugin.js
src/webview/spellchecker.js

Fixes a lot of issues with spellchecker handling (especially on Windows)

[PR] spellchecker improvements

---

src/components/services/content/ServiceWebview.js
src/components/ui/SubscriptionPopup.js

This fixes issue #30 where certain Google Hangout features are no longer functioning.
This patch removes lines in the embedded web view code that disables web security explicitly, allowing the setting to be enabled by default.
In response to issue #30 which details how specific Google Hangout integration with Google Voice does not work when using Franz. Specifically, contact lookups did not work when the contact was a Google Voice contact. The Hangouts' dailer was also non-functional.
Details of the troubleshooting to determine cause are here: https://github.com/meetfranz/recipe-hangouts/issues/5
Tested the build on my Mac (10.12.5) x86_64 after a clean install.
I was able to add a new Hangouts account and all features are functional. I was also able to use all existing accounts (Slack, …

Removing explicit disabling of web security setting for the WebView controls

---

src/stores/ServicesStore.js

[PR] Bugfixing

---

src/lib/Menu.js

fix copy & paste

---

src/models/Recipe.js

catch Error to keep stacktrace
app fails to load with thrown `Error: Version <invalid.semver> of recipe 'xxx' is not a valid semver version` 
by reloading app and checking for warning in console

REMOVE invalid semver version tantrum

---

.vscode/launch.json
src/containers/layout/AppLayoutContainer.js
src/index.js
src/stores/AppStore.js
src/stores/ServicesStore.js
src/webview/plugin.js

Sorting services caused a performance drop due to unnecessary rerendering of the service webviews. 
What do we want? 
> A faster Franz!
How do we do it?
> Make Franz faster!

Improve order performance

---

.vscode/launch.json
package.json
src/api/server/LocalApi.js
src/api/server/ServerApi.js
src/index.html
src/lib/analytics.js
src/stores/RecipesStore.js
src/stores/RequestStore.js
src/stores/ServicesStore.js
yarn.lock

Replacing all console outputs with the `debug` module as we've experienced in the past that in some scenarious the amount of debug logs can have serious performance implications. 
What do we want? 
> A faster Franz!
How do we do it?
> Make Franz faster!
<!---- [ ] My change requires a change to the documentation.

Replace console logs with debugger

---

src/actions/settings.js
src/api/LocalApi.js
src/api/server/LocalApi.js
src/components/settings/settings/EditSettingsForm.js
src/config.js
src/containers/layout/AppLayoutContainer.js
src/containers/settings/EditSettingsScreen.js
src/electron/Settings.js
src/electron/ipc-api/settings.js
src/i18n/locales/en-US.json
src/index.js
src/models/Settings.js
src/models/User.js
src/stores/AppStore.js
src/stores/ServicesStore.js
src/stores/SettingsStore.js
src/stores/UIStore.js
src/stores/UserStore.js
src/webview/plugin.js

In some scenarios the gpu/hardware acceleration is causing a higher energy usage. With this option we enable the option to disable the hardware acceleration. 
Make Franz bettererer.

Add option to disable gpu acceleration

---

CHANGELOG.md
CONTRIBUTING.md
README.md
src/components/auth/Signup.js
src/config.js
src/lib/Menu.js

Just changed some links to https from http and made sure they work. Note: `slack.franz.im` currently has a broken cert up, should probably be looked at and then updated as well. Oh also the GitHub repo description!
#httpsallthethings
I clicked on them and they worked!

convert many links from http to https

---

README.md

Added instructions to the README.md on how to install Franz on macOS using homebrew.
Lots of people use Homebrew, this makes it easier for them to install Franz.
not relevant
not relevant

Add instruction to install Franz with homebrew

---

docs/example-feature/actions.js
docs/example-feature/api.js
docs/example-feature/index.js
docs/example-feature/state.js
docs/example-feature/store.js
src/actions/lib/actions.js
src/api/server/ServerApi.js
src/api/utils/auth.js

This PR adds useful patterns for building standalone app features (developed in the feature/workspace branch) so that we can already start using them for other features.

add useful helpers for building standalone app features

---

package-lock.json
package.json
src/helpers/validation-helpers.js
src/i18n/locales/defaultMessages.json
src/i18n/messages/src/helpers/validation-helpers.json

This PR fixes the problem described in https://github.com/meetfranz/franz/pull/1464

Use same email validation as on the api

---

package-lock.json
package.json

This PR updates two babel polyfill dependencies.

Update minor dependencies

---

src/components/AppUpdateInfoBar.js
src/components/auth/AuthLayout.js
src/components/layout/AppLayout.js
src/containers/auth/AuthLayoutContainer.js
src/dev-app-update.yml
src/i18n/locales/defaultMessages.json
src/i18n/locales/en-US.json
src/i18n/messages/src/components/AppUpdateInfoBar.json
src/i18n/messages/src/components/layout/AppLayout.json
src/i18n/messages/src/lib/Menu.json
src/lib/Menu.js

This PR adds a "Check for updates" menu item under the app menu.
Other improvements:
- updates are also available for unauthenticated users now

Add check for updates menu item

---

src/webview/recipe.js

This PR is based on the great work of @vantezzen in #1621 which fixes #1609 (Broken Skype links)

Fixes #1609 by adding special handling for skype links

---

src/app.js
src/electron/ipc-api/appIndicator.js
src/electron/ipc-api/download.js
src/stores/ServicesStore.js

Electron replaced several function calls with object properties (https://www.electronjs.org/docs/api/modernization/property-updates).
Franz still uses some of these deprecated functions, so this commit will replace these with their new property counterpart.
This commit is only transferring the changes made in getferdi/ferdi#371 and getferdi/ferdi#384 into the upstream repository.

[WIP] Replace/remove deprecated electron function calls

---

appveyor.yml
src/index.js
src/models/Service.js
src/stores/AppStore.js

based on https://github.com/getferdi/ferdi/pull/639
- Origin header was not being sent in the requests that searches users using Google APIs from Franz's webview.
- Add ability for recipes to add headers in any ongoing request from their respective webviews.
- Add ability to copy the host from Referer header, to match origin/referer headers
- Add headers for specific patterns of urls. This can be used to send different headers for different URLs in a recipe's context.
- Add check to identify if the method modifyRequestHeaders is implemented by recipes.
- Send IPC message from models/Service.js to the main process to set the headers if the method is implemented
- Receive the IPC message in index.js and add headers using session.fromPartition(<PartitionName>).webRequest.onBeforeSendHeaders …

added support to modifyRequestHeaders
