meetfranz/franz

package.json
src/components/auth/Import.js
src/stores/UserStore.js

This PR is fixing the service import when signing up for Franz
- Cleared `~/Library/Application Support/Franz/recipes`
- Sign up for a new Franz account
- Select the services you'd like to import
- Checked `~/Library/Application Support/Franz/recipes` if all recipes have been installed
- Checked in _Added Services_ if services have been added

Fix service import

---

src/components/auth/Login.js
src/components/auth/Signup.js
src/styles/infobox.scss

Users consistently report issues about not being able to sign in to their accounts when in dev mode. This is because we're splitting dev and production APIs/DBs to avoid test noise in the production DB.
This PR adds a notice to login and signup to highlight this.

Add dev mode notice to login and signup

---

src/i18n/locales/de.json

Fix #138 by renaming "Taskleiste" to "Systemleiste".
Thos should be more understandable

Rename "Taskleiste" to "Systemleiste", Fix #138

---

src/actions/service.js
src/containers/settings/ServicesScreen.js
src/stores/ServicesStore.js

After navigating away from the services tab in settings, the infobox should go away.
Reset the `actionStatus` of the service store when the service dashboard is unmounted.
Alleviates confusion when a user is navigating through the settings and sees old service changes in the infobox.
Tested on OS X High Sierra
The below still shows when navigating back to the service tab after clicking on a different tab.

Reset status when navigating away from services screen

---

.github/ISSUE_TEMPLATE.md

Hey @adlk ,
I thought it would be beneficial to add to the `ISSUE_TEMPLATE.md` file the usual reply you give to people when they ask for a new recipe through a GitHub issue instead of the form.
That ideally would reduce the number of people doing that!

Added plugin form to issue template

---

src/app.js

Fixes #219 
Disables the `dragover` and `drag` events
Better usability when accidentally dragging into the Franz sidebar
Tested on OSX 10.13

Prevent app from redirecting when dropping link

---

src/webview/lib/RecipeWebview.js
src/webview/notifications.js

`onNotify` was not being called because of scoping
Bug was introduced in 9593b28a7b2c3aa4adb6ccca5d4d2d5bf0b95017. `Notification.onNotify` contains the recipe `onNotify`, but `this.onNotify` is currently called in the franz web view. Changed to modifying `Notification.prototype.onNotify`.
Addresses a bug that results in `onNotify` for messenger not being called.
Tested on OSX High Sierra

Fix setting notification onNotify

---

src/lib/Menu.js

When a service is configured without a name the service app menu will show an empty item. We  fallback to the recipe name including the team id or custom Url.
Closes #250

[PR] Fix empty strings in service menu

---

src/components/services/tabs/Tabbar.js
src/stores/ServicesStore.js

This is my very first open source contribution 😄 
These changes fix two issues related to service tab reordering in the tab bar.
1. Service tabs can be dragged when clicking in the sidebar background
2. After reordering tabs, the previously active tab becomes the current active tab
Fixes #283 
Tested in Windows 10 using development mode (`npm run dev`) and final build (`npm run build`).
Compared sidebar behaviour to current `develop` branch  to ensure no side effects are introduced.

[PR] Fix tabs reordering

---

.github/ISSUE_TEMPLATE.md
src/components/settings/services/EditServiceForm.js
src/models/Service.js

Stripping www from the custom url causes some custom services to fail.
When there is no domain without www loading is not possible.
Resolves: #325

Do not strip www from custom urls

---

src/lib/Menu.js
src/stores/AppStore.js

Takes into consideration which services are displayed in the sidebar even if they are disabled (but not hidden) and computes the correct shortcut number for each one of them.
Fixes https://github.com/meetfranz/franz/issues/350
Tested in Windows 10 64bits. Checked shortcut numbers when the option to show disabled services is checked and when it isn't.

Fix service keyboard shortcut numbering

---

electron-builder.yml
package.json
src/electron/deepLinking.js
src/index.js
src/stores/AppStore.js

Enables external resources to control app routes via eg. `franz://settings/app`.
The available urls reflect the apps routes.
**Todo**

[PR] Add deep linking functionality

---

src/webview/lib/RecipeWebview.js

Some plugins might have bugs where they allow for negative numbers in the badge:
This change is required so that if that bug is present in the plugin at least Franz won't go into negative numbers. Raised issue:
https://github.com/meetfranz/franz/issues/401
This was tested on a Mac. Used the broken Google Calendar plugin (fix for it here: https://github.com/meetfranz/plugins-legacy/pull/332) to replicate the issue:
* go to Google Calendar
* press Escape
* with this fix, the badge number should not decrease (without the fix, it goes into negative numbers)

Fix bug that allows negative badge notifications

---

src/app.js

Since dragging and dropping the window of Franz triggers bubbling (Dragging the window while Whatsapp is open causes the contact info bar to pop up), I used the method "event.stopPropagation()" in "app.js" on the events "dragover" and "drop" to prevent such actions from bubbling.
In response to issue #357, adding these two lines prevent unwanted bubbling events from getting triggered when we try to drag and drop the Franz window frame. Thus, when somone tries to drag the Franz window while Whatsapp is open, the contact info bar will longer pop out.
Closes #357

prevent drag event from bubbling

---

src/stores/ServicesStore.js

This PR fixes an issue with services getting stuck on external sites as Franz is built to display static web apps. 
<kbd>Ctrl/Cmd</kbd>+<kbd>R</kbd> now navigates back to the `service.url` instead of just reloading.

[PR] Reload service root

---

src/stores/AppStore.js

Electron offers support to listen to the computers resume event. This however doesn't work any longer. There is now a custom check to see if the computer was in sleep mode to reload all services.
More information
https://github.com/electron/electron/issues/1615
https://github.com/electron/electron/issues/8560

Fix service reload after waking machine up

---

package.json
src/electron/ipc-api/autoUpdate.js
src/index.js
yarn.lock

Upgrading dependencies to run on the latest version of OSX 10.13.2
`node-sass` v4.5.3 -> v4.7.2 (v4.5.3 is not supported in latest version of OSX)
`electron-spellchecker` v1.2.0 -> v1.1.2 (v1.1.2 is the latest release - https://github.com/electron-userland/electron-spellchecker/releases)
Enables development on the latest version of OSX
Verified that the project compiles and runs on OSX 10.13.2

Update development dependencies

---

src/components/auth/Invite.js
src/components/auth/Login.js
src/components/auth/Password.js
src/components/auth/Signup.js
src/components/ui/Subscription.js
src/containers/settings/EditServiceScreen.js
src/containers/settings/EditUserScreen.js

fixes form validation error messages Franz-wide
when submitting during signup as well as when adding services without field values, no error message appears
all screens with forms tested manually

Fix form validation

---

package.json
src/api/LocalApi.js
src/api/server/LocalApi.js
src/api/server/ServerApi.js
src/models/Settings.js
src/stores/AppStore.js
src/stores/ServicesStore.js
src/stores/SettingsStore.js
src/stores/UserStore.js
yarn.lock

The settingsStores request architecture was too complex and error prone when used with localstorage. localstorage is now used via mobx-localstorage everywhere which allows us to remove all of the `request` design for the `SettingsStore`.
Patching changes in app settings did not work properly when the changed key did not already exist in localstorage. This was also one of the reasons why some settings toggles did not allow to turn off/on.
This refactor is also solving issues with not being able to disable autostart as mentioned in #689 and #629
closes #615, closes #689, closes #629

Refactor settingsStore to use mobx-localstorage

---

src/stores/AppStore.js

I changed the way the window is restored in `src/stores/AppStore.js`.
Fixes issue #645
- Operating System and version: Arch Linux, 4.15.2-2
- Desktop environment: Gnome 3.26.2
Tested with these states : minimized, hidden, maximized minimized, maximized hidden. The fix correctly restores the window with its previous settings.

Correctly restore window when clicking on a notification

---

src/actions/settings.js
src/api/LocalApi.js
src/api/server/LocalApi.js
src/config.js
src/containers/layout/AppLayoutContainer.js
src/containers/settings/EditSettingsScreen.js
src/electron/Settings.js
src/electron/ipc-api/settings.js
src/models/Settings.js
src/models/User.js
src/stores/AppStore.js
src/stores/ServicesStore.js
src/stores/SettingsStore.js
src/stores/UIStore.js
src/stores/UserStore.js
src/webview/plugin.js

To enable certain features like disabling GPU acceleration we need to move certain parts of the app configuration to the main process. 
Additionally to the localStorage stores we are now saving certain app specific configs in settings.json in
- `%APPDATA%\Franz\config` on Windows
- `$XDG_CONFIG_HOME/Franz` or `~/.config/Franz/config` on Linux
- `~/Library/Application Support/Franz/config` on macOS
Ground work for new main-process only features like disable GPU acceleration

Split settings data stores

---

src/index.js

This change was a simple one-liner, just removed minimizeToSystemTray setting check from condition in close event. It's explained below.
It fixes issues #763 and #1006. Both describes a problem that you can't close a window until minimize to system tray is enabled. Which then, as a setting suggests, you loose a minimize to taskbar function. Therefore, minimization setting should not interfere with closing.
With provided code change, window will close as it should, according to "runInBackground" setting it will stay in system tray or will quit. Minimize function will not interfere with this functionality. When "minimize to system tray" enabled, it will only affect the window minimize function with overriding it to minimize to system tray instead, otherwise minimize function will stay …

Remove minimize setting check on close event

---

docs/linux.md

There was a typo in the installation instructions for linux. The command `dnf-install` does not exist. `dnf install` without the dash is the right command to use.

typo: `dnf-install` has to be `dnf install`

---

src/index.js
src/lib/Tray.js
src/stores/AppStore.js

Trying to fix #1300 by myself. Adding Window.restore() and Window.focus() helps addressing minimized window

Fix minimized window focusing

---

src/webview/contextMenu.js

This PR is fixing #1316 which is caused by an electron bug that has a wrong reference to the focused element when accessing `electron.remote.webContents.getFocusedWebContents()`.
- Have a minimum of 2 services and a text in your clipboard
- Go to the second service and try to paste the clipboard content via the right click-context menu.
- Copy, Cut & Paste should work.
This PR closes #1316

Fix windows copy paste context menu on Windows

---

README.md
package-lock.json
package.json

**Fixes**: https://github.com/meetfranz/franz/issues/1317
Update required in order to fix performance degradation due to memory leak issue https://github.com/electron/electron/pull/16772.
Bumps version of electron in `package.json` from 4.0.4 to 4.0.8
Due to a memory leak issue found in version 4.0.4 of electron, host machine resource utilization was going through the roof. 
Ran the local environment with 4.0.4 and then with 4.0.8 and checked CPU temperature sensors.

Update electron to 4.0.8

---

src/features/workspaces/store.js
src/stores/ServicesStore.js

This PR fixes a bug when reordering services (drag & drop) within workspaces.

Fix service reordering within workspaces

---

src/features/announcements/store.js

This PR adds support for multilingual announcements with the following logic:
1. if the announcement json includes the users locale as root key -> take that
2. if there is the default locale defined -> take that
3. If no default locale, treat the announcement as not multilingual and pick root

support multilingual announcements

---

src/stores/GlobalErrorStore.js
src/stores/UserStore.js

This PR fixes a bug so that the user is correctly logged out when the auth token is invalid. Also adds a catch for invalid json responses in the global error store.

logout user when access token is invalid

---

src/features/workspaces/store.js

This PR fixes a bug that happens when there are invalid service references in a workspace `services` array. The fix simply fixes the problem locally by removing the invalid entry after checking that the services have been loaded.

Fix invalid services references in workspaces locally

---

src/features/workspaces/store.js
src/stores/lib/Reaction.js

This PR fixes a bug where the workspaces logic was not properly cleaned-up when a user downgraded his account to free while having an active workspace.

fix reactions and workspace cleanup logic

---

src/features/workspaces/components/WorkspaceDrawer.js
src/features/workspaces/components/WorkspaceDrawerItem.js

This PR is in reference to https://github.com/meetfranz/franz/issues/1569 
There exist keyboard shortcuts to switch between Workspaces but they are not highlighted
This adds tooltips to WorkspaceDrawerItems to highlight their keyboard shortcuts
This is mainly a discovery issue. I opened an issue earlier regarding missing shortcuts. I spent some time trying to figure out the code in order to add the shortcuts myself and found that they already exist. 
Reference: https://github.com/meetfranz/franz/issues/1569 
Ran a build locally on macOS
<del>Could not run lint, facing issues. Although I am pretty sure that this is not going to be an issue for the change</del>

Add tooltip with shortcuts in Workspace Drawer

---

src/components/services/content/Services.js

This PR fixes a small issue with the confetti timeout if the component is unmounted and the timer is not cleared.

Clear confetti timeout on component unmount

---

src/components/services/content/ServiceWebview.js

This PR adds a workaround for a known electron webview issue where the cursor disappears when navigating the page / using inputs: 
https://github.com/electron/electron/issues/14474

Workaround for disappearing cursors in webviews

---

src/webview/spellchecker.js

While Electron <6 still [required a second "autoCorrectWord" argument](https://github.com/electron/electron/blob/v3.1.0/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider) for `webFrame.setSpellCheckProvider`, Electron 6 [no longer needs this argument](https://electronjs.org/docs/api/web-frame#webframesetspellcheckproviderlanguage-provider). 
Because of this, Franz's service webview will throw an error when trying to disable the Spellchecker.
This PR is a simple fix, removing the second argument.
- Run Franz locally and test to disable Spellchecker

Fix disable spell checker method for Electron 6

---

src/config.js
src/index.js

This is an environment variables for Franz (FRANZ_APPDATA_DIR) that I already used in a hard-fork (Ferdi). Where it can change where the folder "Franz" is used/created.
I want this feature to help me to create a better FranzPortable with PortableApps.com format. And for other people who maybe prefer something else of %AppData%.
I already tested with a fork but I will build Franz myself later and confirming is functionnallity.
**UPDATE**: From this [build](https://ci.appveyor.com/project/adlk/franz/builds/28489849); everything is working fine.

Environment variables for portability

---

src/lib/Menu.js

While Electron <6 [used a callback to get the current zoom level](https://github.com/electron/electron/blob/4-1-x/docs/api/webview-tag.md#webviewgetzoomlevelcallback), Electron 6 will [directly return the zoom level without a callback](https://electronjs.org/docs/api/webview-tag#webviewgetzoomlevel). This results in service zoom not working in Franz 5.4.X.
Related:
#1677 
#1673 
This PR will update `src/lib/Menu.js` to use the new syntax for `webview.getZoomLevel()` to enable zooming services to work again.
- Zooming services in and out

Fix zoom not working

---

src/components/ui/FeatureList.js

When starting Franz 5.4.0, it is throwing an error "Invalid argument supplied to oneOf".
Looking into this, the error originates in `src/components/ui/FeatureList.js`, where the PropType for `plan` is set to `config.PLANS`. This constant is an object, but `oneOf` is requiring it to be an array. As it looks like, `FeatureList` is supplied with one of the values of `PLANS` (e.g. "personal" or "pro").
This PR will change the PropType for `plan` to `Object.values(PLANS)`, which will remove the error.
- Starting Franz before and after the fix was applied. Before the error was there, after the fix the error was gone but everything was still working

Fix `plan` PropType in FeatureList
